version: '3'

services:
  influxdb:
    image: influxdb:1.7.3
    ports:
      - 8086:8086
    environment:
      INFLUXDB_DB: iaap
  
  chronograf:
    image: chronograf:1.7.5
    ports:
      - 8888:8888
    depends_on:
      - influxdb
    links:
      - influxdb
  
  grafana:
    image: grafana/grafana:5.3.2
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    links:
      - influxdb
